
#启动路径前缀，方便路由转发
server:
  servlet:
    context-path: /member
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/train?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.cjj.train.member.mapper: debug
  pattern:
    dateformat: HH:mm:ss