POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MDQ0Mzc5OTMsIm1vYmlsZSI6IjEzMDAwMDAwMDAxIiwiaWQiOjE3NDI4Mjc1MDk4MTg0NjIyMDgsImV4cCI6MTcwNDUyNDM5MywiaWF0IjoxNzA0NDM3OTkzfQ.TsvOW77bbN_z8DoVOxhNkI3UHSYsizU3WowmkNN3lEM

{
  "name": "test",
  "idCard": "1234321",
  "type": "2"
}



###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1628627322414436352,
  "memberId": 1624581077500825600,
  "name": "test1",
  "idCard": "123321",
  "type": "1"
}

###

GET http://localhost:8000/member/passenger/query-list
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MDQ0Mzc5OTMsIm1vYmlsZSI6IjEzMDAwMDAwMDAxIiwiaWQiOjE3NDI4Mjc1MDk4MTg0NjIyMDgsImV4cCI6MTcwNDUyNDM5MywiaWF0IjoxNzA0NDM3OTkzfQ.TsvOW77bbN_z8DoVOxhNkI3UHSYsizU3WowmkNN3lEM

###

DELETE http://localhost:8000/member/passenger/delete/1628627401883914240
Accept: application/json
token: {{token}}


